import Menu from './components/Menu/Menu';

const menu: Menu[] = [
    {
        name: 'Салаты',
        iconName: 'salad',
        subcategories: [
            { name: 'Мясные салаты', slug: 'myasnye-salaty' },
            { name: 'Рыбные салаты', slug: 'rybnye-salaty' },
            { name: 'Овощные салаты', slug: 'ovoshchnye-salaty' },
            { name: 'Тёплые салаты', slug: 'teplye-salaty' },
        ],
    },
    {
        name: 'Закуски',
        iconName: 'appetizers',
        subcategories: [
            { name: 'Мясные закуски', slug: 'myasnye-zakuski' },
            { name: 'Рыбные закуски', slug: 'rybnye-zakuski' },
            { name: 'Овощные закуски', slug: 'ovoshchnye-zakuski' },
            { name: 'Теплые закуски', slug: 'teplye-zakuski' },
            { name: 'Бутерброды', slug: 'buterbrody' },
            { name: 'Фастфуд', slug: 'fastfud' },
        ],
    },
    {
        name: 'Первые блюда',
        iconName: 'firstCourse',
        subcategories: [
            { name: 'Мясные супы', slug: 'myasnye-supy' },
            { name: 'Овощные супы', slug: 'ovoshchnye-supy' },
            { name: 'Бульоны', slug: 'bulony' },
            { name: 'Холодные супы', slug: 'kholodnye-supy' },
            { name: 'Диетические супы', slug: 'dieticheskie-supy' },
        ],
    },
    {
        name: 'Вторые блюда',
        iconName: 'mainCourse',
        subcategories: [
            { name: 'Мясные', slug: 'myasnye' },
            { name: 'Рыбные', slug: 'rybnye' },
            { name: 'Овощные', slug: 'ovoshchnye' },
            { name: 'Из птицы', slug: 'iz-ptitsy' },
            { name: 'Из субпродуктов', slug: 'iz-subproduktov' },
            { name: 'На пару', slug: 'na-paru' },
            { name: 'Пельмени, вареники', slug: 'pelmeni-vareniki' },
            { name: 'Мучные гарниры', slug: 'muchnye-garniry' },
            { name: 'Овощные гарниры', slug: 'ovoshchnye-garniry' },
            { name: 'Пюре', slug: 'pyure' },
            { name: 'Суши', slug: 'sushi' },
        ],
    },
    {
        name: 'Десерты, выпечка',
        iconName: 'dessert',
        subcategories: [
            { name: 'Блины и оладьи', slug: 'bliny-i-oladi' },
            { name: 'Пироги и пирожки', slug: 'pirogi-i-pirozhki' },
            { name: 'Торты', slug: 'torty' },
            { name: 'Кексы и маффины', slug: 'keksy-i-maffiny' },
            { name: 'Слойки и ватрушки', slug: 'sloyky-i-vatrushki' },
            { name: 'Из слоёного теста', slug: 'iz-sloenogo-testa' },
            { name: 'Из заварного теста', slug: 'iz-zavarnogo-testa' },
            { name: 'Из дрожжевого теста', slug: 'iz-drozhzhevogo-testa' },
            { name: 'Булочки и сдоба', slug: 'bulochki-i-sdoba' },
            { name: 'Хлеб', slug: 'khleb' },
            { name: 'Тесто на пиццу', slug: 'testo-na-pitstsu' },
            { name: 'Кремы', slug: 'kremy' },
        ],
    },
    {
        name: 'Блюда на гриле',
        iconName: 'grilled',
        subcategories: [
            { name: 'Говядина', slug: 'govyadina' },
            { name: 'Свинина', slug: 'svinina' },
            { name: 'Птица', slug: 'ptitsa' },
            { name: 'Рыба', slug: 'ryba' },
            { name: 'Овощи', slug: 'ovoshchi' },
        ],
    },
    {
        name: 'Веганская кухня',
        iconName: 'vegan',
        subcategories: [
            { name: 'Закуски', slug: 'zacuski' },
            { name: 'Первые блюда', slug: 'pervye-blyuda' },
            { name: 'Вторые блюда', slug: 'vtoroe-blyuda' },
            { name: 'Десерты', slug: 'deserty' },
            { name: 'Выпечка', slug: 'vypechka' },
            { name: 'Сыроедческие блюда', slug: 'syroedicheskie-blyuda' },
        ],
    },
    {
        name: 'Детские блюда',
        iconName: 'children',
        subcategories: [
            { name: 'Первые блюда', slug: 'pervye-blyuda' },
            { name: 'Вторые блюда', slug: 'vtoroe-blyuda' },
            { name: 'Гарниры', slug: 'garniry' },
            { name: 'Выпечка', slug: 'vypechka' },
            { name: 'Без глютена', slug: 'bez-glyutena' },
            { name: 'Без аллергенов', slug: 'bez-allergenov' },
        ],
    },
    {
        name: 'Лечебное питание',
        iconName: 'therapeuticNutrition',
        subcategories: [
            { name: 'Диета №1', slug: 'dieta-1' },
            { name: 'Диета №2', slug: 'dieta-2' },
            { name: 'Диета №3', slug: 'dieta-3' },
            { name: 'Диета №5', slug: 'dieta-5' },
            { name: 'Диета №6', slug: 'dieta-6' },
            { name: 'Диета №7', slug: 'dieta-7' },
            { name: 'Диета №8', slug: 'dieta-8' },
            { name: 'Диета №9', slug: 'dieta-9' },
            { name: 'Диета №10', slug: 'dieta-10' },
            { name: 'Диета №11', slug: 'dieta-11' },
            { name: 'Диета №12', slug: 'dieta-12' },
            { name: 'Диета №13', slug: 'dieta-13' },
            { name: 'Диета №14', slug: 'dieta-14' },
            { name: 'Без глютена', slug: 'bez-glyutena' },
            { name: 'Без аллергенов', slug: 'bez-allergenov' },
        ],
    },
    {
        name: 'Национальные',
        iconName: 'national',
        subcategories: [
            { name: 'Американская кухня', slug: 'amerikanskaya-kukhnya' },
            { name: 'Арабская кухня', slug: 'arabskaya-kukhnya' },
            { name: 'Греческая кухня', slug: 'grecheskaya-kukhnya' },
            { name: 'Грузинская кухня', slug: 'gruzinskaya-kukhnya' },
            { name: 'Итальянская кухня', slug: 'italyanskaya-kukhnya' },
            { name: 'Испанская кухня', slug: 'ispanskaya-kukhnya' },
            { name: 'Китайская кухня', slug: 'kitayskaya-kukhnya' },
            { name: 'Мексиканская кухня', slug: 'meksikanskaya-kukhnya' },
            { name: 'Паназиатская кухня', slug: 'panaziatskaya-kukhnya' },
            { name: 'Русская кухня', slug: 'russkaya-kukhnya' },
            { name: 'Турецкая кухня', slug: 'turetskaya-kukhnya' },
            { name: 'Узбекская кухня', slug: 'uzbekskaya-kukhnya' },
            { name: 'Японская кухня', slug: 'yaponskaya-kukhnya' },
            { name: 'Другая кухня', slug: 'drugaya-kukhnya' },
        ],
    },
    {
        name: 'Соусы',
        iconName: 'sauce',
        subcategories: [
            { name: 'Соусы мясные', slug: 'sousy-myasnye' },
            { name: 'Соусы сырные', slug: 'sousy-syrnye' },
            { name: 'Маринады', slug: 'marinady' },
        ],
    },
    {
        name: 'Напитки',
        iconName: 'drink',
        subcategories: [
            { name: 'Соки и фреши', slug: 'soki-i-freshi' },
            { name: 'Смузи', slug: 'smuzi' },
            { name: 'Компоты', slug: 'kompoty' },
            { name: 'Кисели', slug: 'kiseli' },
            { name: 'Кофе', slug: 'kofe' },
            { name: 'Лютебный чай', slug: 'lyutebnyy-chay' },
            { name: 'Квас', slug: 'kvas' },
            { name: 'Коктейли', slug: 'kokteyli' },
            { name: 'Алкогольные', slug: 'alkogolnye' },
        ],
    },
    {
        name: 'Заготовки',
        iconName: 'preserve',
        subcategories: [
            { name: 'Мясные заготовки', slug: 'myasnye-zagotovki' },
            { name: 'Рыбные заготовки', slug: 'rybnye-zagotovki' },
            { name: 'Из огуцов', slug: 'iz-ogutsov' },
            { name: 'Из томатов', slug: 'iz-tomatov' },
            { name: 'Из грибов', slug: 'iz-gribov' },
            { name: 'Солёные заготовки', slug: 'solenye-zagotovki' },
            { name: 'Салаты, икра', slug: 'salaty-ikra' },
            { name: 'Из фруктов и ягод', slug: 'iz-fruktov-i-yagod' },
        ],
    },
];

export default menu;
